### PR TITLE
Added oindrillac to byon maintainers

### PR DESCRIPTION
**Pull request by oindrillac**
SSIA

### CODE REVIEW

**Comment by codificat** [comment]
/test peribolos
(trying to capture the logs, which are not visible at the moment due to temporary relocation of the prow object storage)

**Comment by codificat** [comment]
> (trying to capture the logs, which are not visible at the moment due to temporary relocation of the prow object storage)

the peribolos check is failing with:
```
Configuration failed: failed to configure open-services-group teams: failed to update sp-peribolos-maintainers members: failed to list 5729504(sp-peribolos-maintainers) members: return code not 2XX: 404 Not Found
```

which I'm not sure what's about...

<details>
<summary>Full log</summary>

```json
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "Throttle(300, 100, *)",
  "severity": "info",
  "time": "2022-03-01T19:16:18Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetOrg(open-services-group)",
  "severity": "info",
  "time": "2022-03-01T19:16:18Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "ListOrgInvitations(open-services-group)",
  "severity": "info",
  "time": "2022-03-01T19:16:20Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "User()",
  "severity": "info",
  "time": "2022-03-01T19:16:20Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "ListOrgMembers(open-services-group, admin)",
  "severity": "info",
  "time": "2022-03-01T19:16:21Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "ListOrgMembers(open-services-group, member)",
  "severity": "info",
  "time": "2022-03-01T19:16:22Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "UpdateOrgMembership(open-services-group, xtuchyna, false)",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:501",
  "func": "main.configureOrgMembers.func1",
  "level": "info",
  "msg": "Set xtuchyna as a member of open-services-group",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "UpdateOrgMembership(open-services-group, shreekarss, false)",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:501",
  "func": "main.configureOrgMembers.func1",
  "level": "info",
  "msg": "Set shreekarss as a member of open-services-group",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepos(open-services-group, false)",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepo(open-services-group, byon)",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:1052",
  "func": "main.configureRepos",
  "level": "info",
  "msg": "repo exists, considering an update",
  "repo": "byon",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepo(open-services-group, community)",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:1052",
  "func": "main.configureRepos",
  "level": "info",
  "msg": "repo exists, considering an update",
  "repo": "community",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepo(open-services-group, devsecops)",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:1052",
  "func": "main.configureRepos",
  "level": "info",
  "msg": "repo exists, considering an update",
  "repo": "devsecops",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepo(open-services-group, metrics)",
  "severity": "info",
  "time": "2022-03-01T19:16:24Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:1052",
  "func": "main.configureRepos",
  "level": "info",
  "msg": "repo exists, considering an update",
  "repo": "metrics",
  "severity": "info",
  "time": "2022-03-01T19:16:25Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "GetRepo(open-services-group, peribolos-as-a-service)",
  "severity": "info",
  "time": "2022-03-01T19:16:25Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:1052",
  "func": "main.configureRepos",
  "level": "info",
  "msg": "repo exists, considering an update",
  "repo": "peribolos-as-a-service",
  "severity": "info",
  "time": "2022-03-01T19:16:25Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "ListTeams(open-services-group)",
  "severity": "info",
  "time": "2022-03-01T19:16:25Z"
}
{
  "client": "github",
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/github/client.go:891",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "ListTeamMembers(5729504, member)",
  "severity": "info",
  "time": "2022-03-01T19:16:26Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:209",
  "func": "main.main",
  "level": "fatal",
  "msg": "Configuration failed: failed to configure open-services-group teams: failed to update sp-peribolos-maintainers members: failed to list 5729504(sp-peribolos-maintainers) members: return code not 2XX: 404 Not Found",
  "severity": "fatal",
  "time": "2022-03-01T19:16:32Z"
}
{
  "component": "entrypoint",
  "error": "wrapped process failed: exit status 1",
  "file": "prow/entrypoint/run.go:80",
  "func": "k8s.io/test-infra/prow/entrypoint.Options.Run",
  "level": "error",
  "msg": "Error executing test process",
  "severity": "error",
  "time": "2022-03-01T19:16:32Z"
}
```
</details>

**Comment by tumido** [comment]
Maybe a hiccup? The team mentioned in the logs exists... https://github.com/orgs/open-services-group/teams/sp-peribolos-maintainers

image

/retest peribolos

**Comment by oindrillac** [comment]
I see in the logs:
```json
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:501",
  "func": "main.configureOrgMembers.func1",
  "level": "info",
  "msg": "Set xtuchyna as a member of open-services-group",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:501",
  "func": "main.configureOrgMembers.func1",
  "level": "info",
  "msg": "Set shreekarss as a member of open-services-group",
  "severity": "info",
  "time": "2022-03-01T19:16:23Z"
}
```
Is it something to do with @xtuchyna and @shreekarSS not being a part of this [group](https://github.com/orgs/open-services-group/people)?

**Pull request merged**
