### PR TITLE
updating meeting link SIG Data Science

### PR DESCRIPTION
**Pull request by schwesig**
https added to create an external link

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
since this doc is auto-generated from [sigs.yaml](https://github.com/open-services-group/community/blob/main/sigs.yaml), should the links be modified there too?

**Comment by MichaelClifford** [comment]
yes, I think this change needs to be made in the `sigs.yaml` then run the autogeneration before submitting the PR: 

`podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev`

**Review by harshad16 — COMMENTED** [review]
lgtm

**Comment by schwesig** [comment]
> since this doc is auto-generated from [sigs.yaml](https://github.com/open-services-group/community/blob/main/sigs.yaml), should the links be modified there too?

I am sorry, you are right. My bad.

**Comment by schwesig** [comment]
sig.yaml updated at https://github.com/open-services-group/community/pull/41

**Pull request closed without merging**
