### PR TITLE
https added to meet.google links

### PR DESCRIPTION
**Pull request by schwesig**
without https:// the links are relative inside the rep

### CODE REVIEW

**Comment by schwesig** [comment]
this PR replaces https://github.com/open-services-group/community/pull/37

**Review by oindrillac — COMMENTED** [review]
👍 /lgtm

@schwesig until we have #26 in place, can you please run `podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev` so that the auto-generated markdown files get updated.

**Comment by MichaelClifford** [comment]
@schwesig can you run 
`podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev` and add the generated files as well?

**Comment by schwesig** [comment]
> +1 /lgtm
> 
> @schwesig until we have #26 in place, can you please run `podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev` so that the auto-generated markdown files get updated.

I did, all should be fine

**Review by oindrillac — APPROVED** [review]
/lgtm

**Pull request merged**
