### PR TITLE
feat(sig-services): Add guideline template

### PR DESCRIPTION
**Pull request by tumido**
As discussed on sig-services we need a common template for the guidelines produced by our SIG.

/hold
please review all

/cc @goern @Shreyanand @KPostOffice @suppathak @codificat @chauhankaranraj @mimotej @SamoKopecky @harshad16 @Gkrumbach07 @aakankshaduggal @schwesig

### CODE REVIEW

**Review by SamoKopecky — COMMENTED** [review]
/lgtm

**Review by SamoKopecky — APPROVED** [review]

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Review by Shreyanand — COMMENTED** [review]
/lgtm

**Review by mimotej — COMMENTED** [review]
/lgtm

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

It looks straight forward. Too short to be true 😉
Like it.

**Pull request merged**
